name: Release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      -
        name: Build and push Redis 6.2.6
        id: docker_build_6
        uses: docker/build-push-action@v2
        with:
          build-args: |
            REDIS_VERSION=6.2.6
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            flyio/redis:6.2.6
            flyio/redis:6.2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
